"""
Simple Calibration Helper
==========================
View transformer kalibrlash uchun eng oddiy ikki bosqichli yo'l:

BOSQICH 1: Freymni rasm sifatida saqlash
    python tools/calibration_helper.py extract --video input_videos/match.mp4

    Natija: calibration_frame.png yaratiladi

BOSQICH 2: Rasmda 4 burchakni topib (Paint/GIMP/PyCharm Image Viewer'da
mouse-over qilib koordinatani ko'ring), keyin saqlash:

    python tools/calibration_helper.py save \\
        --p1 "X1,Y1" --p2 "X2,Y2" --p3 "X3,Y3" --p4 "X4,Y4" \\
        --preset half_pitch

    Tartibi (juda muhim):
        p1 = pastki-chap (orqa chiziq + chap yon chiziq)
        p2 = yuqori-chap (markaz chizig'i + chap yon chiziq)
        p3 = yuqori-o'ng (markaz chizig'i + o'ng yon chiziq)
        p4 = pastki-o'ng (orqa chiziq + o'ng yon chiziq)

PRESET'LAR (4 burchak orasidagi haqiqiy maydon o'lchami):
    full_pitch    105 × 68 m   (butun maydon)
    half_pitch     52.5 × 68 m  (yarim maydon - eng tavsiya etiladi)
    penalty_box    40.32 × 16.5 m (jarima maydonchasi)
    center_circle  18.3 × 18.3 m (markaziy doira atrofi)

NIMA UCHUN BU OSON?
    PyCharm Pro Image Viewer'da rasmni ochib, mouse'ni harakatlantirsangiz,
    pastki o'ngdagi statusbar'da koordinata ko'rinadi. Yoki shunday onlayn
    asboblar bor: https://www.image-map.net/ , https://imagemapper.online/

NATIJA: view_transformer/calibration.json yaratiladi.
ViewTransformer avtomatik shu fayldan o'qiydi.
"""
import argparse
import json
import os
import sys
import cv2
import numpy as np


PRESETS = {
    'full_pitch':   (105.0, 68.0),
    'half_pitch':   (52.5, 68.0),
    'penalty_box':  (40.32, 16.5),
    'center_circle': (18.3, 18.3),
}


def extract_frame(video_path, frame_num=0, output='calibration_frame.png'):
    """Videodan freym chiqarib, rasm sifatida saqlash"""
    if not os.path.exists(video_path):
        print(f"❌ Video topilmadi: {video_path}")
        return False

    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        print(f"❌ Video ochilmadi: {video_path}")
        return False

    cap.set(cv2.CAP_PROP_POS_FRAMES, frame_num)
    ret, frame = cap.read()
    cap.release()

    if not ret:
        print(f"❌ {frame_num}-freym o'qilmadi")
        return False

    cv2.imwrite(output, frame)
    h, w = frame.shape[:2]
    print(f"✅ Freym saqlandi: {output}")
    print(f"   Rezolyutsiya: {w} × {h}")
    print(f"   Endi rasmni oching va 4 burchakning koordinatasini topib oling.")
    print(f"   PyCharm Pro: Image Viewer'da mouse pozitsiyasini ko'rasiz.")
    print(f"   GIMP: Tools -> Measure")
    print(f"   Paint: cursor pozitsiyasi pastdagi statusbar'da")
    return True


def parse_point(s):
    """\"X,Y\" -> [X, Y]"""
    try:
        x, y = s.split(',')
        return [int(float(x.strip())), int(float(y.strip()))]
    except (ValueError, AttributeError):
        raise argparse.ArgumentTypeError(f"Noto'g'ri format: '{s}'. Misol: '110,1035'")


def save_calibration(p1, p2, p3, p4, preset='half_pitch',
                     output='view_transformer/calibration.json',
                     world_length=None, world_width=None):
    """4 nuqtani va preset'ni JSON ga yozish"""
    if preset == 'custom':
        if world_length is None or world_width is None:
            print("❌ custom preset bilan --world-length va --world-width kerak")
            return False
        wl, ww = world_length, world_width
    elif preset in PRESETS:
        wl, ww = PRESETS[preset]
    else:
        print(f"❌ Noma'lum preset: {preset}. Available: {list(PRESETS.keys())}")
        return False

    pixel_vertices = [p1, p2, p3, p4]

    # target_vertices tartibi (view_transformer.py konventsiyasiga mos):
    # p1 (pastki-chap)   -> (0, world_width)
    # p2 (yuqori-chap)   -> (0, 0)
    # p3 (yuqori-o'ng)   -> (world_length, 0)
    # p4 (pastki-o'ng)   -> (world_length, world_width)
    target_vertices = [
        [0.0, ww],
        [0.0, 0.0],
        [wl, 0.0],
        [wl, ww],
    ]

    cal = {
        'pixel_vertices': pixel_vertices,
        'target_vertices': target_vertices,
        'world_length': float(wl),
        'world_width': float(ww),
        'preset': preset,
        'note': 'Auto-generated by tools/calibration_helper.py',
    }

    os.makedirs(os.path.dirname(output), exist_ok=True)
    with open(output, 'w', encoding='utf-8') as f:
        json.dump(cal, f, indent=2, ensure_ascii=False)

    print(f"✅ Kalibrlash saqlandi: {output}")
    print(f"   Preset: {preset} ({wl}m × {ww}m)")
    print(f"   p1 (pastki-chap):  {p1}")
    print(f"   p2 (yuqori-chap):  {p2}")
    print(f"   p3 (yuqori-o'ng):  {p3}")
    print(f"   p4 (pastki-o'ng):  {p4}")
    print()
    print("Endi ViewTransformer ni qayta ishga tushiring (`python main.py`).")
    print("Eski stub fayllarini ham yangilash kerak: rm stubs/*.pkl")
    return True


def visualize_calibration(image_path, calibration_path, output='calibration_check.png'):
    """Kalibrlashni vizual tekshirish - 4 nuqtani rasmga chizish"""
    if not os.path.exists(calibration_path):
        print(f"❌ {calibration_path} topilmadi")
        return False

    with open(calibration_path) as f:
        cal = json.load(f)

    img = cv2.imread(image_path)
    if img is None:
        print(f"❌ {image_path} topilmadi yoki rasm emas")
        return False

    pts = cal['pixel_vertices']
    colors = [(0, 0, 255), (0, 255, 0), (255, 0, 0), (255, 255, 0)]
    labels = ['p1 (BL)', 'p2 (TL)', 'p3 (TR)', 'p4 (BR)']

    # Polygon chizish
    poly = np.array(pts, dtype=np.int32)
    overlay = img.copy()
    cv2.fillPoly(overlay, [poly], (0, 255, 100))
    img = cv2.addWeighted(overlay, 0.25, img, 0.75, 0)
    cv2.polylines(img, [poly], isClosed=True, color=(0, 255, 0), thickness=3)

    # Har nuqtani aylana va label bilan
    for i, (pt, color, label) in enumerate(zip(pts, colors, labels)):
        cv2.circle(img, tuple(pt), 12, color, -1)
        cv2.circle(img, tuple(pt), 14, (255, 255, 255), 2)
        cv2.putText(img, label, (pt[0] + 18, pt[1] + 6),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255, 255, 255), 3)
        cv2.putText(img, label, (pt[0] + 18, pt[1] + 6),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.7, color, 2)

    cv2.imwrite(output, img)
    print(f"✅ Vizualizatsiya: {output}")
    print(f"   Yashil to'rtburchak siz ko'rsatgan kalibrlangan zona.")
    print(f"   Bu maydonning bir qismiga to'g'ri kelishi kerak.")
    return True


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                      formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest='cmd', required=True)

    p_extract = sub.add_parser('extract', help='Videodan freym chiqarish')
    p_extract.add_argument('--video', required=True)
    p_extract.add_argument('--frame', type=int, default=0)
    p_extract.add_argument('--output', default='calibration_frame.png')

    p_save = sub.add_parser('save', help='Kalibrlashni saqlash')
    p_save.add_argument('--p1', type=parse_point, required=True,
                         help='Pastki-chap nuqta, masalan "110,1035"')
    p_save.add_argument('--p2', type=parse_point, required=True,
                         help='Yuqori-chap nuqta')
    p_save.add_argument('--p3', type=parse_point, required=True,
                         help='Yuqori-o\'ng nuqta')
    p_save.add_argument('--p4', type=parse_point, required=True,
                         help='Pastki-o\'ng nuqta')
    p_save.add_argument('--preset', default='half_pitch',
                         choices=list(PRESETS.keys()) + ['custom'])
    p_save.add_argument('--world-length', type=float, default=None,
                         help='custom preset uchun (metr)')
    p_save.add_argument('--world-width', type=float, default=None,
                         help='custom preset uchun (metr)')
    p_save.add_argument('--output', default='view_transformer/calibration.json')

    p_check = sub.add_parser('check', help='Kalibrlashni vizual tekshirish')
    p_check.add_argument('--image', default='calibration_frame.png')
    p_check.add_argument('--calibration', default='view_transformer/calibration.json')
    p_check.add_argument('--output', default='calibration_check.png')

    args = parser.parse_args()

    if args.cmd == 'extract':
        ok = extract_frame(args.video, args.frame, args.output)
        sys.exit(0 if ok else 1)
    elif args.cmd == 'save':
        ok = save_calibration(
            args.p1, args.p2, args.p3, args.p4,
            preset=args.preset, output=args.output,
            world_length=args.world_length, world_width=args.world_width,
        )
        sys.exit(0 if ok else 1)
    elif args.cmd == 'check':
        ok = visualize_calibration(args.image, args.calibration, args.output)
        sys.exit(0 if ok else 1)


if __name__ == '__main__':
    main()
